dataset:
  kind: conll2003
  uri: s3://traal-storage/experiments/conll2003-full
  n_jobs: 10
  sample_al: false

wandb:
  entity: dslarionov
  project: traal

experiment:
  group: conll2003-full

model:
  name: distilbert-base-cased
  min_updates_per_epoch: 20
  n_trials: 10